made first example of solution
Sashk52/movie-theatre pull request #1
Opened 2021-01-26 19:05 UTC by Sashk52

2021-01-26 21:22 UTC, Fedich09 requested changes

2021-01-26 21:22 UTC, Fedich09 commented on src/main/java/com/dev/movietheatre/dao/impl/MovieDaoImpl.java
> +            throw new RuntimeException("Can't insert Movie entity", e);
```suggestion
            throw new RuntimeException("Can't insert Movie entity" + movie, e);
```
and add own exception

2021-01-26 21:22 UTC, Fedich09 commented on src/main/java/com/dev/movietheatre/dao/impl/MovieDaoImpl.java
> +            throw new RuntimeException("Can't get list of all movies ", e);
```suggestion
            throw new RuntimeException("Can't get list of all movies ", e);
```
add own exception

2021-01-26 21:22 UTC, Fedich09 commented on src/main/java/com/dev/movietheatre/util/HibernateUtil.java
> +            throw new RuntimeException("Error creating session Factory", e);
```suggestion
            throw new RuntimeException("Error creating session Factory", e);
```
same here

2021-01-26 21:22 UTC, Fedich09 commented on src/main/resources/hibernate.cfg.xml
> +</hibernate-configuration>
add empty line

2021-01-27 06:29 UTC, Sashk52 commented on src/main/resources/hibernate.cfg.xml
> +</hibernate-configuration>
done

2021-01-27 06:29 UTC, Sashk52 commented on src/main/java/com/dev/movietheatre/util/HibernateUtil.java
> +            throw new RuntimeException("Error creating session Factory", e);
done

2021-01-27 06:29 UTC, Sashk52 commented on src/main/java/com/dev/movietheatre/dao/impl/MovieDaoImpl.java
> +            throw new RuntimeException("Can't get list of all movies ", e);
done

2021-01-27 06:29 UTC, Sashk52 commented on src/main/java/com/dev/movietheatre/dao/impl/MovieDaoImpl.java
> +            throw new RuntimeException("Can't insert Movie entity", e);
done

2021-01-27 07:46 UTC, Fedich09 approved these changes

2021-01-27 07:47 UTC, Sofasmile approved these changes

2021-01-28 09:31 UTC, merged